BstLabs/py-clvm

- src/pyclvm/instance/start.py
- src/pyclvm/instance/stop.py
- src/pyclvm/ssm/session/ls.py
- src/pyclvm/ssm/shell.py
> Added more detailed state checks for starting/stopping instances

- src/pyclvm/__init__.py
- src/pyclvm/_clvm.py
- src/pyclvm/_common/signal_handler.py
- src/pyclvm/instance/start.py
- src/pyclvm/instance/stop.py
- src/pyclvm/ssm/session/ls.py
- src/pyclvm/ssm/session/start.py
- src/pyclvm/ssm/session/stop.py
- src/pyclvm/ssm/shell.py
Releasing v1.0.1 version
Fixes #15 
Fixes #17 
> Release PR v1.0.1

- src/pyclvm/ssm/session/start.py
> Changed usage of proc.stderr according to doc

- src/pyclvm/instance/_process.py
- src/pyclvm/instance/ls.py
- src/pyclvm/redirect/start.py
- src/pyclvm/redirect/stop.py
- src/pyclvm/ssh/new.py
- src/pyclvm/ssm/session/ls.py
- src/pyclvm/ssm/session/start.py
- src/pyclvm/ssm/session/stop.py
- src/pyclvm/ssm/shell.py
- src/pyclvm/vscode/start.py
> now passing a session to mappings of ec2map to adapt to its change

- src/pyclvm/vscode/start.py
Fixes #108
Refactoring and eliminating the duplicated code portions.
> Fixed the subprocess.Popen call issue

- src/pyclvm/ssh/new.py
> Added the platform=aws to the ssh command in ssh/config file

- src/pyclvm/plt.py
> Eliminated multiple cache file hit and platform choice

- src/pyclvm/ssh/new.py
Desc:
- Modified updating ssh config to take the CLVM path dynamically
without platform dependency
Fixes #126
> Proxy command takes full path of CLVM

- src/pyclvm/_common/session_aws.py
- src/pyclvm/vscode/start.py
> fixed the failed MFA prompt in VSCODE

- pyproject.toml
- src/pyclvm/_common/azure_instance_proxy.py
- src/pyclvm/ssh/start.py
Realize features #109 #127 on Azure. Start VM on "clvm ssh start" command.
> Issue #109, #127 start VM on "ssh start"

- src/pyclvm/redirect/__init__.py
- src/pyclvm/redirect/start.py
- src/pyclvm/redirect/stop.py
> Refactored port mapping

- pyproject.toml
- src/pyclvm/vscode/adjust.py
Introduced new command:
`clvm vscode adjust`
Fixes #130 
> Editing global vscode settings for Linux

- src/pyclvm/_common/gcp_instance_proxy.py
- src/pyclvm/ssh/new.py
> issue-116, remove sshconfig lib, substitute Crypto lib for MacOS compatibility

- src/pyclvm/ssh/new.py
- src/pyclvm/ssh/start.py
Fixes #146 
Refactor command "clvm ssh start ..." for GCP
> Issue-146, refactor command "clvm ssh start ..." for GCP

- src/pyclvm/connect.py
Fixes #144 VM starts on "clvm connect ..." now
> Issue-144 VM starts on "clvm connect ..." now

- .gitignore
- pyproject.toml
- src/pyclvm/_common/session_gcp.py
Fixes #142 GCP default credentials
> Issue-142 Fix GCP Default Credentials misunderstanding bug

- src/pyclvm/_common/session_gcp.py
An addition for #141, add exception on get_instances.
> GCP Default credentials. Add exception on get_instances

- src/pyclvm/plt.py
- src/pyclvm/vscode/adjust.py
Fixes #153 
Fix "clvm vscode adjust" for Windows
> Issue-153, add some WIndows compatibility

- src/pyclvm/_common/session_azure.py
- src/pyclvm/_common/session_gcp.py
- src/pyclvm/login.py
- src/pyclvm/plt.py
Add login command for GCP and Azure for Windows and MacOS
> Issue-154 Add the new command "login"

- src/pyclvm/_common/azure_instance_proxy.py
- src/pyclvm/_common/gcp_instance_proxy.py
- src/pyclvm/ssh/new.py
- src/pyclvm/ssh/start.py
Fixes #157 "clvm ssh" commands fail on Windows
Also MacOS "clvm ssh ..." fixed
> Issue-157, "clvm ssh" commands fail on Windows

- src/pyclvm/ssh/new.py
- src/pyclvm/vscode/adjust.py
Fixes #159 "clvm ssh ..." commands don't switch platform by the fitst time
> Issue-159, "clvm ssh ..." commands don't switch platform by the fitst time

- pyproject.toml
- src/pyclvm/__init__.py
- src/pyclvm/_clvm.py
- src/pyclvm/_common/gcp_instance_proxy.py
- src/pyclvm/instance/start.py
- src/pyclvm/instance/stop.py
- src/pyclvm/redirect/__init__.py
- src/pyclvm/redirect/start.py
- src/pyclvm/redirect/stop.py
- src/pyclvm/ssh/new.py
- src/pyclvm/vscode/adjust.py
Fixed #159 
Fixed #157 
Fixed #153
Fixed #125 
Resolved #154 
Resolved #155
> Release PR v1.1.5

- src/pyclvm/_common/azure_instance_proxy.py
Fixes #164 Supress traceback on "clvm connect ..." on Azure
> Issue-164, suppress annoying traceback

- src/pyclvm/ssh/new.py
> Issue-167, fix ssh config mess

- src/pyclvm/_common/session_aws.py
- src/pyclvm/ssh/new.py
Fixes #115 AWS ignores non-default profile
> Issue-115, AWS ignores non-default profile

- src/pyclvm/__init__.py
- src/pyclvm/_clvm.py
- src/pyclvm/connect.py
- src/pyclvm/instance/command.py
- src/pyclvm/instance/start.py
- src/pyclvm/instance/stop.py
- src/pyclvm/login.py
- src/pyclvm/plt.py
- src/pyclvm/redirect/__init__.py
- src/pyclvm/redirect/start.py
- src/pyclvm/ssh/new.py
- src/pyclvm/ssh/restore.py
- src/pyclvm/ssh/start.py
- src/pyclvm/ssm/clear.py
- src/pyclvm/vscode/install.py
> Release PR v1.1.7

- pyproject.toml
- scripts/type.sh
- src/pyclvm/ssh/new.py
Fixes #191 
Added `Changelog` link to PyPi
Description:
- Modified pyproject.toml and added `Changelog` link next to Home and Source
> Feat(PyPi): Added `Changelog` link to PyPi

- .github/workflows/changelog.yml
- CHANGELOG.md
- pyproject.toml
- scripts/type.sh
- src/pyclvm/__init__.py
- src/pyclvm/_clvm.py
- src/pyclvm/configure/__init__.py
- src/pyclvm/configure/aws.py
- src/pyclvm/ssh/new.py
Description:
- Initial version only supports AWS local configuration
- It uses subprocesses to call aws cli under the hood
- It detects OS and adapts the params accordingly
- Error handling was added as well
Fixes #196
> Feat(config): Implemented first version of `configure`

- src/pyclvm/configure/aws.py
Description:
- Defined a new function to handle info message
- Fixed a minor typo
Fixes #200
> Feat(general): Added a reminder for prerequisites for `configure aws`

- src/pyclvm/_common/session_azure.py
Fixes: #205 Jdict json serialization codec corrupts azure-mgmt-* serialization process.
> Issue-205; Fix jdict codec serialization bug

- CHANGELOG.md
* [#209](https://github.com/BstLabs/py-clvm/pull/209): Docs(update): Modified and enhanced existing documentation
> [Changelog CI] Add Changelog for Version v1.1.10b

- .github/workflows/changelog.yml
- CHANGELOG.md
- changelog-ci-config.json
- src/pyclvm/__init__.py
- src/pyclvm/_clvm.py
- src/pyclvm/_common/azure_instance_mapping.py
- src/pyclvm/_common/azure_instance_proxy.py
- src/pyclvm/_common/azure_rest_api.py
- src/pyclvm/_common/session_azure.py
- src/pyclvm/instance/ls.py
- src/pyclvm/instance/start.py
- src/pyclvm/instance/stop.py
- src/pyclvm/login.py
Makes Azure operation faster due to using REST API
Fixes: #149
> Issue-149; Make Azure operation faster due to using REST API

- src/pyclvm/_common/azure_instance_proxy.py
- src/pyclvm/connect.py
- src/pyclvm/instance/command.py
- src/pyclvm/ssh/start.py
Fixes: #112 Thread with azure tunnel keeps working after closing vscode
> Issue-112; Fix. Thread with azure tunnel keeps working after closing vscode

- src/pyclvm/_common/azure_instance_proxy.py
- src/pyclvm/ssh/new.py
- src/pyclvm/ssh/start.py
> Feat: Realise multiple SSH connections for Azure VMs

- .github/workflows/changelog.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/type.yml
- CHANGELOG.md
- README.md
- src/pyclvm/ssh/new.py
* removed unrelated kwarg from being passed to execute command
* better print for seperator
* removed unused `import time`
Fixes #227 
> Fix: unrelated kwarg being passed to execute command

- CHANGELOG.md
- pyproject.toml
- src/pyclvm/__init__.py
- src/pyclvm/_clvm.py
- src/pyclvm/_common/session_azure.py
- src/pyclvm/install/__init__.py
- src/pyclvm/install/aws.py
- src/pyclvm/instance/command.py
- src/pyclvm/login.py
- src/pyclvm/ssh/new.py
- Changed the instance argument type to `Ec2RemoteShellProxy`
- Changed `kwargs.get()` method to `kwargs.pop()`method to not send extra params to the other function calls
Fixes #236
> Fix: Resolved type error on `clvm instance command`

- src/pyclvm/instance/command.py
- src/pyclvm/ssh/new.py
- Command stdout is visible on host terminal now
> Fix: Fixed command execution stdout
